# -*- coding: utf-8 -*-
"""EvaParcial2_los3sigmas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8t4d-x0-PDigYm5WH-AF7hCaGXBVSgI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, StandardScaler
from sklearn.model_selection import cross_val_score, StratifiedKFold, GridSearchCV, RandomizedSearchCV, train_test_split
from sklearn.svm import SVC
from sklearn.cluster import KMeans, DBSCAN
from sklearn.metrics import davies_bouldin_score, silhouette_score, accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix
from sklearn.utils import resample
import warnings
from sklearn.exceptions import UndefinedMetricWarning
warnings.filterwarnings('ignore', category=UserWarning)
warnings.filterwarnings('ignore', category=UndefinedMetricWarning)

#Nota: Tiempo aproximado para correr todo el codigo: 6 minutos
df = pd.read_csv('/content/games.csv')
df = df.drop_duplicates().copy()
df.head(3)

#Dejamos los datos mas relevantes para predecir el rating de un juego
df_relevante = df[["rating", "positive_ratio","user_reviews", "price_original"]].copy()
df_relevante.head(3)

#No es necesario hacer un tratamiento de nulos
df_relevante.info()

#ENCODING rating
ordinal_encoder = OrdinalEncoder(categories=[['Overwhelmingly Negative', 'Mostly Negative', 'Very Negative','Negative', 'Mixed', 'Positive','Very Positive', 'Mostly Positive', 'Overwhelmingly Positive']])

#Transformar el rating label a jerarquico numerico
df_relevante['rating'] = ordinal_encoder.fit_transform(df_relevante[['rating']])

X = df_relevante[['positive_ratio', 'user_reviews', 'price_original']]
y = df_relevante['rating']

# Split del dataset completo
X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Muestra reducida solo para CV y GridSearchCV
# SVM tiene complejidad, lo que hace inviable entrenar sobre 50k de filas
# usamos stratify=y_train_full para mantener la distribucion original
X_sample, y_sample = resample(X_train_full, y_train_full, n_samples=10000, random_state=42, stratify=y_train_full)

# Dividimos la muestra para obtener el set de entrenamiento que usaremos para los hiperparámetros.
X_train, _, y_train, _ = train_test_split(X_sample, y_sample, test_size=0.2, random_state=42)

"""# Modelo Supervisado"""

#Definimos los modelos supervisados a evaluar
pipelines = {
    "Random Forest": Pipeline([
        ("scaler", StandardScaler()),
        ("model", RandomForestClassifier(random_state=42))
    ]),
    "SVM": Pipeline([
        ("scaler", StandardScaler()),
        ("model", SVC(random_state=42, probability=True))
    ]),
    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(random_state=42, max_iter=1000))
    ])
}

#Usamos Stratified para asegurar que cada partición respete la distribución original de las clases
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

baseline_results = {}

#Evaluacion comparativa de modelos (Baseline)
for nombre, pipeline in pipelines.items():
    #Usamos Stratified para asegurar que cada partición respete la distribución original de las clases
    scores_acc = cross_val_score(pipeline, X_sample, y_sample, cv=cv, scoring="accuracy")
    scores_f1 = cross_val_score(pipeline, X_sample, y_sample, cv=cv, scoring="f1_weighted")

    # Guardamos el promedio y desviación estándar para evaluar estabilidad del modelo
    baseline_results[nombre] = {
        "accuracy_mean": scores_acc.mean(),
        "accuracy_std":  scores_acc.std(),
        "f1_mean":       scores_f1.mean(),
        "f1_std":        scores_f1.std()
    }
    print(f"{nombre}: Accuracy={scores_acc.mean():.3f} ± {scores_acc.std():.3f} | F1={scores_f1.mean():.3f} ± {scores_f1.std():.3f}")

# Comparar los 3 modelos visualmente
nombres = list(baseline_results.keys())
acc_means = [baseline_results[n]["accuracy_mean"] for n in nombres]
acc_stds  = [baseline_results[n]["accuracy_std"]  for n in nombres]
f1_means  = [baseline_results[n]["f1_mean"]       for n in nombres]

x = np.arange(len(nombres))
width = 0.35 # Ancho de las barras

fig, ax = plt.subplots(figsize=(10, 5))
# Graficamos Accuracy con barras de error (yerr) para visualizar la variabilidad/estabilidad
bars1 = ax.bar(x - width/2, acc_means, width, yerr=acc_stds, capsize=5,
               label="Accuracy", color="steelblue")
# Graficamos F1-Score para contrastar con el Accuracy
bars2 = ax.bar(x + width/2, f1_means,  width, capsize=5,
               label="F1", color="coral")

# Configuración de estética y etiquetas
ax.set_xticks(x)
ax.set_xticklabels(nombres)
ax.set_ylim(0, 1)
ax.set_ylabel("Score")
ax.set_title("Comparación Baseline — 3 Modelos Supervisados (CV=5)")
ax.legend()
plt.tight_layout()
plt.show()

# Optimizacion de hiperparametros

# Definición grid de parámetros para cada modelo.
# Nota: Se usa el prefijo 'model__' para referenciar el componente del Pipeline.
param_grids = {
    "Random Forest": {
        "model__n_estimators": [100, 200],
        "model__max_depth":    [None, 10, 20],
        "model__min_samples_split": [2, 5]
    },
    "SVM": {
        "model__C":      [0.1, 1],
        "model__kernel": ["rbf", "linear"]
    },
    "Logistic Regression": {
        "model__C":       [0.01, 0.1, 1, 10],
        "model__solver":  ["lbfgs", "saga"]
    }
}

best_models = {}

# Ejecución de GridSearchCV para encontrar la mejor combinación de parámetros
for nombre, pipeline in pipelines.items():
    grid = GridSearchCV(
        pipeline,
        param_grids[nombre],
        cv=cv,
        scoring="f1_weighted",
        n_jobs=-1
    )
    # Entrenamos con el set de entrenamiento (X_train, y_train)
    grid.fit(X_train, y_train)
    # Guardamos el objeto grid con los params y resultados
    best_models[nombre] = grid
    print(f"{nombre} — mejores params: {grid.best_params_}")
    print(f"F1 CV: {grid.best_score_:.3}\n")

# Evaluamos cada modelo optimizado sobre el conjunto de prueba
final_results = {}

# Iteramos sobre los mejores modelos encontrados por GridSearchCV
for nombre, grid in best_models.items():
    # Realizamos predicciones sobre datos
    y_pred = grid.predict(X_test)

    # Almacenamos métricas clave para la comparación final
    final_results[nombre] = {
        "accuracy":  accuracy_score(y_test, y_pred),
        "f1":        f1_score(y_test, y_pred, average="weighted"),
        "precision": precision_score(y_test, y_pred, average="weighted", zero_division=0),
        "recall":    recall_score(y_test, y_pred, average="weighted", zero_division=0)
    }

    print(f"\n{'='*40}")
    print(f"  {nombre}")
    print(f"{'='*40}")
    print(classification_report(y_test, y_pred, zero_division=0))

#Analisis de errores (Matrices de confusion)
# Visualizamos cómo se distribuyen las predicciones frente a los valores reales

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

for ax, (nombre, grid) in zip(axes, best_models.items()):
    # Predicción sobre el conjunto de test para evaluar generalización
    y_pred = grid.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)

    # Visualización con Heatmap
    # annot=True: Muestra los números en las celdas
    # fmt="d": Formato de número entero (decimal)
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", ax=ax)
    ax.set_title(f"Matriz de Confusión\n{nombre}")
    ax.set_xlabel("Predicho")
    ax.set_ylabel("Real")

plt.tight_layout()
plt.show()

# Resumen de metricas de modelo supervisado

df_resultados_supervisado = pd.DataFrame(final_results).T.round(3)
df_resultados_supervisado.index.name = "Modelo"
print("\nResumen final — métricas en test set:")
print(df_resultados_supervisado.to_string())



"""# Modelo no supervisado

## 1. KMEANS
"""

scaler = StandardScaler()
X_clustering = scaler.fit_transform(X)

#Optimizacion de clusterin (Elbow Method)
# Encontrar el valor ideal de 'k' balanceando la cohesion de los grupos y la complejidad del modelo.
inertias = []
k_range = range(2, 11) # Evaluamos desde 2 hasta 10 clusters

for k in k_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X_clustering)
    # La inercia mide qué tan compactos son los clusters (menor es mejor)
    inertias.append(km.inertia_)

plt.figure(figsize=(8, 4))
plt.plot(k_range, inertias, marker='o', color='steelblue')
plt.xlabel("Número de clusters (k)")
plt.ylabel("Inercia")
plt.title("Elbow Method — KMeans")
plt.xticks(k_range)
plt.tight_layout()
plt.show()

#Validacion de clustering con silhouette score
silhouette_scores = []

for k in k_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(X_clustering)
    # Calculamos el silhouette score para el conjunto completo
    silhouette_scores.append(silhouette_score(X_clustering, labels))

plt.figure(figsize=(8, 4))
plt.plot(k_range, silhouette_scores, marker='o', color='coral')
plt.xlabel("Numero de clusters (k)")
plt.ylabel("Silhouette Score")
plt.title("Silhouette Score por k — KMeans")
plt.xticks(k_range)
plt.tight_layout()
plt.show()

"""**Conclusión: usamos k=4 (4 clusters) es el balance entre separación real de clusters y granularidad útil.**"""

#Entrenamiento final de kmeans
# Tras analizar con elbow y el silhouette score, seleccionamos k=4
# como el numero optimo de clusters para segmentar el dataset.
kmeans_final = KMeans(n_clusters=4, random_state=42, n_init=10)
labels_kmeans = kmeans_final.fit_predict(X_clustering)

labels_sample = kmeans_final.predict(X_clustering)

# 1. Silhouette Score: Mide qué tan cerca está cada punto de su propio cluster (ideal cercano a 1).
sil_kmeans = silhouette_score(X_clustering, labels_sample)

# 2. Davies-Bouldin Score: Mide la relación entre la dispersión intra-cluster y la separación inter-cluster (ideal valores bajos)
db_kmeans = davies_bouldin_score(X_clustering, labels_sample)

print(f"KMeans (k=4)")
print(f"  Silhouette Score : {sil_kmeans:.3f}")
print(f"  Davies-Bouldin   : {db_kmeans:.3f}")

# Visualizacion de clusters
# Graficamos los resultados para observar como KMeans ha segmentado los juegos
# basándose en su ratio de positividad y su volumen de reseñas.
fig, ax = plt.subplots(figsize=(9, 5))

scatter = ax.scatter(
    X_clustering[:, 0],
    X_clustering[:, 1],
    c=labels_sample,
    cmap='tab10',
    alpha=0.4,
    s=10
)

colors = ['tab:blue', 'tab:orange', 'tab:pink', 'tab:red']
labels_legend = [f'Cluster {i}' for i in range(4)]
patches = [mpatches.Patch(color=colors[i], label=labels_legend[i]) for i in range(4)]
ax.legend(handles=patches, title='Cluster', loc='upper left')

ax.set_xlabel("positive_ratio (escalado)")
ax.set_ylabel("user_reviews (escalado)")
ax.set_title("Clusters KMeans (k=4) — positive_ratio vs user_reviews")
ax.set_ylim(-1, 10)
plt.tight_layout()
plt.show()

"""## 2. DBSCAN"""

# Clustering basado en densidad (DBSCAN)

# eps=0.35: Radio máximo para considerar a dos puntos como vecinos.
# min_samples=10: Cantidad mínima de puntos para formar una región densa (cluster).
dbscan = DBSCAN(eps=0.35, min_samples=10, n_jobs=-1)
labels_dbscan = dbscan.fit_predict(X_clustering)

# Analisis del resultado de DBSCAN
# Calculamos el número de clusters y el total de outliers.
n_clusters_db = len(set(labels_dbscan)) - (1 if -1 in labels_dbscan else 0)
n_outliers_db = (labels_dbscan == -1).sum()

print(f"DBSCAN — clusters encontrados : {n_clusters_db}")
print(f"DBSCAN — outliers detectados  : {n_outliers_db} ({n_outliers_db/len(labels_dbscan)*100:.1f}%)")

# Validacion de clusters
if n_clusters_db > 1:
    sil_db = silhouette_score(X_clustering, labels_dbscan)
    db_db  = davies_bouldin_score(X_clustering, labels_dbscan)
    print(f"Silhouette Score : {sil_db:.3f}")
    print(f"Davies-Bouldin   : {db_db:.3f}")
else:
    print("DBSCAN no encontró clusters suficientes")

#Visualizacion del resultado de DBSCAN

# En este grafico diferenciamos claramente los grupos densos (clusters) de los
# puntos aislados (outliers/ruido) identificados por el algoritmo.
fig, ax = plt.subplots(figsize=(9, 5))

# Creamos máscaras booleanas para separar los datos agrupados del ruido
mask_outliers = labels_dbscan == -1
mask_clusters = ~mask_outliers

scatter = ax.scatter(
    X_clustering[mask_clusters, 0],
    X_clustering[mask_clusters, 1],
    c=labels_dbscan[mask_clusters],
    cmap='tab10',
    alpha=0.4,
    s=10,
    label='Clusters'
)
ax.scatter(
    X_clustering[mask_outliers, 0],
    X_clustering[mask_outliers, 1],
    c='black',
    alpha=0.6,
    s=10,
    label=f'Outliers ({mask_outliers.sum()})'
)

ax.set_xlabel("positive_ratio (escalado)")
ax.set_ylabel("user_reviews (escalado)")
ax.set_title("Clusters DBSCAN — positive_ratio vs user_reviews")
ax.set_ylim(-1, 10)
ax.legend(loc='upper left')
plt.tight_layout()
plt.show()

# Comparación final entre ambos métodos no supervisados
resumen_clustering = pd.DataFrame({
    "KMeans (k=4)":    {"Clusters": 4,  "Outliers (%)": "N/A",  "Silhouette": 0.456, "Davies-Bouldin": 0.627},
    "DBSCAN (eps=0.35)": {"Clusters": 8, "Outliers (%)": "0.5%", "Silhouette": 0.566, "Davies-Bouldin": 1.706}
}).T

resumen_clustering.index.name = "Modelo"
print("Comparación final — Modelos No Supervisados")
print(resumen_clustering.to_string())